trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:

# ✅ BUILD STAGE
- stage: Build
  displayName: "Build Stage"
  jobs:
  - job: BuildJob
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: "Install dependencies"


- stage: Test
  displayName: "Test Stage"
  dependsOn: Build
  jobs:
  - job: TestJob
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'

    - script: |
        pip install pytest
        pytest
      displayName: "Run Tests"